### PR TITLE
Fix Ogemaw bug

### LINKED ISSUE #76: Debug Ogemaw Template Issue
image
Issue is most likely in prop funds table, statement of net positions. Update this issue as we test.

Tested on:

- [x] Commit [2836159](https://github.com/closup/process-xbrl/pull/26/commits/2836159e7e27261644cc10c7b11b39a1baf5f968) and it passed / no errors.
- [ ] Commit [20356e](https://github.com/closup/process-xbrl/commit/20356ee58eb2444eebd8c3e7d77c2ddae0eb41c3) fails with same error. This commit merges the commit above to the original template (but I think it's also being merged by other stuff like #27 .
`ValueError: Per-column arrays must each be 1-dimensional` being called by prop_funds_table.py > net_position.py

Tried:
- Rewrite some code in .py files to avoid error -> gets too complicated and more errors appear.
- Save the table read in in table.py before a call to `pd.melt` where it fails. [full_dataframe_before_melt.csv](https://github.com/user-attachments/files/16289769/full_dataframe_before_melt.csv). A comparison between csv that Clayton.xlsx and 20356e generates is this 
image
So it could be an issue with not reading in the table and the first row properly.

### PR DESCRIPTION
**Pull request by kwheelan**
# Closes #76 

@lucakato @sarraha786 

## Fixes

- I found and deleted some random numbers in row 80 of the `PropFund Stmt of Rev Exp and Ch` sheet (at least in the filled version of the Ogemaw template that Luca sent me). 
- The `PropFundsTable` class was incorrectly calculating the number of header lines. I adjusted the class to just inherit the `Table` method for this function.
- I also suppressed the persistent `openpyxl` and `arelle` warnings to make debugging easier. 
- Added a try-except block to `Table.py` to give more coherent error messages when a sheet fails to parse.

@lucakato Could you please confirm that the sheet parses using the code on `76-debug-ogemaw` (you'll have to delete the extra numbers on your version of the Excel file). If it works, please mark this request as ready to merge.

## Remaining Issues

There are still a few independent errors. I'll create separate issues for these to avoid cluttering this PR:
 - We'll need to adjust the empty template to make sure those random numbers are gone (#80).
 - The Javascript for the file upload gives a minor error (#81)
 - The viewer isn't working correctly because it can't access the `ixbrlviewer.js` script (#82)
 - Arelle gives errors because the Python hasn't yet been edited to handle the template changes in #62 (errors to be fixed in #83)

### CODE REVIEW

**Comment by lucakato** [comment]
@kwheelan Thanks for noticing the numbers on line 80, I removed it, tested it against the code on the branch and the Ogemaw template converts. However, now it fails for Clayton when I use this [Clayton.Excel.xlsx](https://github.com/user-attachments/files/16326645/Clayton.Excel.xlsx) file.

In this [commit](https://github.com/closup/process-xbrl/commit/8f35d3e4a7883d09a94321f4d65be4484785bb31) you removed the `n_header_lines()` function but are you sure we don't need it? I think the Clayton one fails giving me this image because `reshape_data()` function in `table.py` relies on `n_header_lines()`. 
Here's the error I get:
image

Pasting in the `reshape_data()` function code:
`
    def reshape_data(self) -> None:
        """
        Process Excel sheet data to extract values and cell locations
        """
        print('top of reshape_data')
        # Clean column names
        self._df.columns = self._df.iloc[self.n_header_lines()].apply(clean)
        # Drop unneeded rows (above taggable portion)
        self._df.drop(index = self._df.index[:self.n_header_lines() + 1], inplace=True)
        
        # Record original row number
        self._df.reset_index(drop=True, inplace=True)
        self._df["row"] = 1 + self.n_header_lines() + len(self.header()) + self._df.index  
        n_rows_orig = len(self._df) # num of rows before reshaping

        # Reshape using 'melt' to give one row per taggable item
        id_cols = self._df.columns[:self.extra_left_cols].tolist() + ["row"]
        val_cols = self._df.columns[self.extra_left_cols:].tolist()
        self._df = pd.melt(self._df, id_vars=id_cols, value_vars=val_cols, var_name="header")

        # Calculate original sheet column and cell in Excel document
        self._df['col'] = [ALPHABET[i] for i in (self.extra_left_cols + (self._df.index // n_rows_orig))]
        cells = [f'{c}{r}' for c, r in zip(self._df['col'], self._df["row"])]
        self._df["id"] = [f'{self.sheet_name.replace(" ", "")}_{cell}' for cell in cells]
        self._df = self._df.sort_values(by=['row', 'col'])  

`

**Comment by kwheelan** [comment]
@lucakato I deleted the `n_header_lines` function only in `prop_funds_table`, but it remains in `table.py`. The PropFundsTable class will inherit the method from the Table class. 

However, the error you get does seem to be related to miscalculating the number of header lines. The issue is that the proprietary funds statements for Clayton don't have a total column, but Ogenaw does. `n_header_lines()` uses the last column to calculate its value. To fix this, we'll need to write a more robust implementation of `n_header_lines()` (in `table.py`). It should probably take the first column and calculate how many rows are above the cell 'XBRL Element'. 

I can implement this later today and tag you when I finish.

**Comment by kwheelan** [comment]
@lucakato I've made that change. Could you please test again on your end? Thanks. I've also added another 'remaining issue' to correctly handle the new custom tags Sarrah added to the template (right now arelle gives parsing errors for those line items).

**Comment by lucakato** [comment]
@kwheelan It works on my end now! Thanks.

**Comment by kwheelan** [comment]
@lucakato Great! Will you mark this as ready to merge? Thanks

**Review by lucakato — APPROVED** [review]
Works.

**Pull request merged**
